a.out : test.o CLConditionVariable.o CLCriticalSection.o CLEvent.o CLExecutive.o CLExecutiveCommunication.o CLExecutiveFunctionForMsgLoop.o CLExecutiveFunctionProvider.o CLExecutiveInitialFinishedNotifier.o CLExecutiveNameServer.o CLLibExecutiveInitializer.o CLLogger.o CLMessage.o CLMessageLoopManager.o CLMessageObserver.o CLMessageQueueBySTLqueue.o CLMsgLoopManagerForSTLqueue.o CLMutex.o CLMutexByPThread.o CLMutexByRecordLocking.o CLMutexByRecordLockingAndPThread.o CLMutexInterface.o CLNonThreadForMsgLoop.o CLProcess.o CLProcessFunctionForExec.o CLSharedMemory.o CLStatus.o CLThread.o CLThreadCommunicationBySTLqueue.o CLThreadForMsgLoop.o CLThreadInitialFinishedNotifier.o 
	g++ -o a.out test.o CLConditionVariable.o CLCriticalSection.o CLEvent.o CLExecutive.o CLExecutiveCommunication.o CLExecutiveFunctionForMsgLoop.o CLExecutiveFunctionProvider.o CLExecutiveInitialFinishedNotifier.o CLExecutiveNameServer.o CLLibExecutiveInitializer.o CLLogger.o CLMessage.o CLMessageLoopManager.o CLMessageObserver.o CLMessageQueueBySTLqueue.o CLMsgLoopManagerForSTLqueue.o CLMutex.o CLMutexByPThread.o CLMutexByRecordLocking.o CLMutexByRecordLockingAndPThread.o CLMutexInterface.o CLNonThreadForMsgLoop.o CLProcess.o CLProcessFunctionForExec.o CLSharedMemory.o CLStatus.o CLThread.o CLThreadCommunicationBySTLqueue.o CLThreadForMsgLoop.o CLThreadInitialFinishedNotifier.o -g -lpthread
	rm *.o

test.o : test.cpp
	g++ -o test.o -c test.cpp -Iinclude -g

CLConditionVariable.o : src/CLConditionVariable.cpp
	g++ -o CLConditionVariable.o -c src/CLConditionVariable.cpp -Iinclude -g

CLCriticalSection.o : src/CLCriticalSection.cpp
	g++ -o CLCriticalSection.o -c src/CLCriticalSection.cpp -Iinclude -g

CLEvent.o : src/CLEvent.cpp
	g++ -o CLEvent.o -c src/CLEvent.cpp -Iinclude -g

CLExecutive.o : src/CLExecutive.cpp
	g++ -o CLExecutive.o -c src/CLExecutive.cpp -Iinclude -g

CLExecutiveCommunication.o : src/CLExecutiveCommunication.cpp
	g++ -o CLExecutiveCommunication.o -c src/CLExecutiveCommunication.cpp -Iinclude -g

CLExecutiveFunctionForMsgLoop.o : src/CLExecutiveFunctionForMsgLoop.cpp
	g++ -o CLExecutiveFunctionForMsgLoop.o -c src/CLExecutiveFunctionForMsgLoop.cpp -Iinclude -g

CLExecutiveFunctionProvider.o : src/CLExecutiveFunctionProvider.cpp
	g++ -o CLExecutiveFunctionProvider.o -c src/CLExecutiveFunctionProvider.cpp -Iinclude -g

CLExecutiveInitialFinishedNotifier.o : src/CLExecutiveInitialFinishedNotifier.cpp
	g++ -o CLExecutiveInitialFinishedNotifier.o -c src/CLExecutiveInitialFinishedNotifier.cpp -Iinclude -g

CLExecutiveNameServer.o : src/CLExecutiveNameServer.cpp
	g++ -o CLExecutiveNameServer.o -c src/CLExecutiveNameServer.cpp -Iinclude -g

CLLibExecutiveInitializer.o : src/CLLibExecutiveInitializer.cpp
	g++ -o CLLibExecutiveInitializer.o -c src/CLLibExecutiveInitializer.cpp -Iinclude -g

CLLogger.o : src/CLLogger.cpp
	g++ -o CLLogger.o -c src/CLLogger.cpp -Iinclude -g

CLMessage.o : src/CLMessage.cpp
	g++ -o CLMessage.o -c src/CLMessage.cpp -Iinclude -g

CLMessageLoopManager.o : src/CLMessageLoopManager.cpp
	g++ -o CLMessageLoopManager.o -c src/CLMessageLoopManager.cpp -Iinclude -g

CLMessageObserver.o : src/CLMessageObserver.cpp
	g++ -o CLMessageObserver.o -c src/CLMessageObserver.cpp -Iinclude -g

CLMessageQueueBySTLqueue.o : src/CLMessageQueueBySTLqueue.cpp
	g++ -o CLMessageQueueBySTLqueue.o -c src/CLMessageQueueBySTLqueue.cpp -Iinclude -g

CLMsgLoopManagerForSTLqueue.o : src/CLMsgLoopManagerForSTLqueue.cpp
	g++ -o CLMsgLoopManagerForSTLqueue.o -c src/CLMsgLoopManagerForSTLqueue.cpp -Iinclude -g

CLMutex.o : src/CLMutex.cpp
	g++ -o CLMutex.o -c src/CLMutex.cpp -Iinclude -g

CLMutexByPThread.o : src/CLMutexByPThread.cpp
	g++ -o CLMutexByPThread.o -c src/CLMutexByPThread.cpp -Iinclude -g

CLMutexByRecordLocking.o : src/CLMutexByRecordLocking.cpp
	g++ -o CLMutexByRecordLocking.o -c src/CLMutexByRecordLocking.cpp -Iinclude -g

CLMutexByRecordLockingAndPThread.o : src/CLMutexByRecordLockingAndPThread.cpp
	g++ -o CLMutexByRecordLockingAndPThread.o -c src/CLMutexByRecordLockingAndPThread.cpp -Iinclude -g

CLMutexInterface.o : src/CLMutexInterface.cpp
	g++ -o CLMutexInterface.o -c src/CLMutexInterface.cpp -Iinclude -g

CLNonThreadForMsgLoop.o : src/CLNonThreadForMsgLoop.cpp
	g++ -o CLNonThreadForMsgLoop.o -c src/CLNonThreadForMsgLoop.cpp -Iinclude -g

CLProcess.o : src/CLProcess.cpp
	g++ -o CLProcess.o -c src/CLProcess.cpp -Iinclude -g

CLProcessFunctionForExec.o : src/CLProcessFunctionForExec.cpp
	g++ -o CLProcessFunctionForExec.o -c src/CLProcessFunctionForExec.cpp -Iinclude -g

CLSharedMemory.o : src/CLSharedMemory.cpp
	g++ -o CLSharedMemory.o -c src/CLSharedMemory.cpp -Iinclude -g

CLStatus.o : src/CLStatus.cpp
	g++ -o CLStatus.o -c src/CLStatus.cpp -Iinclude -g

CLThread.o : src/CLThread.cpp
	g++ -o CLThread.o -c src/CLThread.cpp -Iinclude -g

CLThreadCommunicationBySTLqueue.o : src/CLThreadCommunicationBySTLqueue.cpp
	g++ -o CLThreadCommunicationBySTLqueue.o -c src/CLThreadCommunicationBySTLqueue.cpp -Iinclude -g

CLThreadForMsgLoop.o : src/CLThreadForMsgLoop.cpp
	g++ -o CLThreadForMsgLoop.o -c src/CLThreadForMsgLoop.cpp -Iinclude -g

CLThreadInitialFinishedNotifier.o : src/CLThreadInitialFinishedNotifier.cpp
	g++ -o CLThreadInitialFinishedNotifier.o -c src/CLThreadInitialFinishedNotifier.cpp -Iinclude -g

